version: "3.1"
services:
  node-app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGO_USER=luiggy
      - MONGO_PASSWORD=luiggy
      - SESSION_SECRET=luiggy

    depends_on:
      - mongo
    volumes:
      - .:/app
      - /app/node_modules

  mongo:
    image: mongo
    # ports:
    # - "27017:27017"
    volumes:
      - mongo-db:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root

  redis:
    image: redis

volumes:
  mongo-db:
